# Generated by Django 6.0.2 on 2026-02-17 13:48

import attendance_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('rfid', 'RFID'), ('fingerprint', 'Fingerprint'), ('hybrid', 'Hybrid')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('lastSeen', models.DateTimeField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='Certificate', max_length=20)),
                ('level', models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20, null=True)),
                ('duration', models.IntegerField(validators=[attendance_api.models.validate_integer])),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regNumber', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('hasRfid', models.BooleanField(default=False)),
                ('hasFingerprint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hasRfid', models.BooleanField(default=False)),
                ('hasFingerprint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('qualification', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('programs', models.ManyToManyField(related_name='courses', to='attendance_api.program')),
            ],
        ),
    ]
