# Generated by Django 6.0.2 on 2026-02-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qualification',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='Certificate', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance_api.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='qualification',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='Certificate', max_length=20),
        ),
    ]
