# Generated by Django 6.0.2 on 2026-02-16 17:55

import attendance_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0006_course_qualification_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.IntegerField(validators=[attendance_api.models.validate_integer]),
        ),
    ]
