# Generated by Django 6.0.2 on 2026-02-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0007_alter_program_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
