# Generated by Django 6.0.2 on 2026-02-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0008_remove_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='attendance_api.program'),
        ),
    ]
